---
## @file
# @date 2025
# @copyright ItSANgo@gmail.com
#   SPDX-License-Identifier: MIT
- name: Setup ECPG
  hosts: localhost
  tasks:
    - name: Install packages
      become: true
      ansible.builtin.apt:
        name:
          - postgresql-all
          - postgresql-client
          - libecpg-dev
          - gcc
          - make
...
